name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  nightly-build:
    name: Nightly Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Apply dart format and commit fixes
        run: |
          # Apply dart format
          dart format .

          # Check if there are any changes
          if ! git diff --quiet; then
            echo "🔧 Formatting changes detected, committing fixes..."
            git config --local user.email "nightly@github.com"
            git config --local user.name "Nightly Build Bot"
            git add .
            git commit -m "🎨 Nightly auto-fix: Apply dart format [skip ci]"
            git push
          else
            echo "✅ No formatting changes needed"
          fi

      - name: Run comprehensive tests
        run: |
          flutter test --coverage
          flutter analyze --fatal-infos

      - name: Build all platforms
        run: |
          flutter build apk --release
          flutter build web --release

      - name: Security audit
        run: dart pub audit
        continue-on-error: true

      - name: Upload nightly artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-builds-${{ github.run_number }}
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/web/
          retention-days: 7
